version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    image: qure_assignment
    expose:
      - 8000
    ports:
      - "8000:8000"
