# Generated by Django 3.1.7 on 2021-03-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
